# Generated by Django 4.2.6 on 2023-10-19 13:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_leavetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='EmpId',
            field=models.CharField(default='default_value', max_length=10),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='FirstName',
            field=models.CharField(default='Paul', max_length=100),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='LastName',
            field=models.CharField(default='Santos', max_length=100),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='PostingDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leavetype',
            name='Status',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpId', models.CharField(default='default_value', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.employee')),
            ],
        ),
    ]
