# Generated by Django 4.2.6 on 2023-10-19 20:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_leavetype_empid_leavetype_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='CreationDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
