# Generated by Django 4.2.6 on 2023-10-20 11:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_department_creationdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(default='Annual', max_length=100),
        ),
        migrations.AddField(
            model_name='leave',
            name='posting_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
