# Generated by Django 4.2.6 on 2023-10-20 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0007_remove_employee_address_remove_employee_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default='800100', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(default='Mombasa', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='dob',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
