# Generated by Django 4.2.6 on 2023-10-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_employee_address_employee_city_employee_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='status',
        ),
    ]
