# Generated by Django 4.2.6 on 2023-10-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0009_remove_leave_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
    ]
