# Generated by Django 4.2.6 on 2023-10-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0011_employee_gender_leave_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_leave_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(default='Annual', max_length=100)),
                ('description', models.TextField(default='Describe leave type', max_length=100)),
            ],
        ),
    ]
