# Generated by Django 4.2.6 on 2023-10-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0016_remove_employee_empcode_alter_employee_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='id',
            new_name='emocode',
        ),
    ]
