# Generated by Django 4.2.6 on 2023-10-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0017_rename_id_employee_emocode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='emocode',
            new_name='empcode',
        ),
    ]
