# Generated by Django 4.2.6 on 2023-10-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0021_alter_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='fromdate',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='leave',
            name='todate',
            field=models.DateField(default=None),
        ),
    ]
