# Generated by Django 4.2.6 on 2023-10-26 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0022_leave_fromdate_leave_todate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='EmpId',
            new_name='empcode',
        ),
    ]
