# Generated by Django 4.2.6 on 2023-10-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0024_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(default='Annual', max_length=100),
        ),
    ]
