# Generated by Django 4.2.6 on 2023-10-26 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0025_alter_leave_leave_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='empcode',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='fromdate',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='todate',
        ),
    ]
