# Generated by Django 4.2.6 on 2023-10-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0026_remove_leave_empcode_remove_leave_fromdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('Union', 'Union'), ('Non-Union', 'Non-Union'), ('Others', 'Others')], default='Non-Union', max_length=10),
        ),
    ]
