# Generated by Django 4.2.6 on 2023-10-27 21:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0027_employee_employee_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='CreationDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
