# Generated by Django 4.2.6 on 2023-10-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0028_admin_creationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='empcode',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
