# Generated by Django 4.2.6 on 2023-10-28 12:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0029_alter_employee_empcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='fromdate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='todate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(default='80100', max_length=255),
        ),
    ]
