# Generated by Django 4.2.6 on 2023-10-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0032_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='isread',
            field=models.IntegerField(default=0),
        ),
    ]
