# Generated by Django 4.2.6 on 2023-10-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0033_leave_isread'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='leave',
            name='leavetype',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
