# Generated by Django 4.2.6 on 2023-10-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0035_alter_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavetype',
            old_name='LeaveType',
            new_name='leavetype',
        ),
    ]
