# Generated by Django 4.2.6 on 2023-10-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0037_alter_admin_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='PostingDate',
            new_name='CreationDate',
        ),
    ]
