# Generated by Django 4.2.6 on 2023-11-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0039_alter_leave_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='fromdate',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='leave',
            name='todate',
            field=models.DateField(default=None),
        ),
    ]
