# Generated by Django 4.2.6 on 2023-11-10 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0043_department_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='user',
            new_name='admin',
        ),
    ]
