# Generated by Django 4.2.6 on 2023-11-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0045_remove_department_admin_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='admin_remark',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
